# Generated by Django 4.2 on 2023-05-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllAvto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_avto', models.CharField(max_length=30)),
                ('production_year', models.CharField(max_length=4)),
                ('probeg', models.CharField(max_length=7)),
                ('kuzov', models.CharField(max_length=10)),
                ('engin_capacity', models.CharField(max_length=3)),
                ('engen_power', models.CharField(max_length=3)),
                ('fuel', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=4)),
                ('privod', models.CharField(max_length=10)),
                ('cvet_avto', models.CharField(max_length=10)),
                ('complectation', models.CharField(max_length=20)),
                ('cena', models.CharField(max_length=8)),
                ('photo_avto_1', models.ImageField(upload_to='image/')),
                ('photo_avto_2', models.ImageField(upload_to='image/')),
                ('photo_avto_3', models.ImageField(upload_to='image/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_question_date', models.DateField()),
                ('call_question_type', models.CharField(max_length=100)),
                ('call_mod_car', models.CharField(max_length=50)),
                ('call_customer_name', models.CharField(max_length=15)),
                ('call_customer_phnum', models.CharField(max_length=16)),
                ('call_customer_comment', models.TextField()),
                ('call_personal_info', models.BooleanField()),
                ('call_personal_reklama', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_vin_number', models.CharField(max_length=17)),
                ('service_mod_avto', models.CharField(max_length=20)),
                ('service_work_type', models.CharField(max_length=100)),
                ('service_date', models.DateTimeField()),
                ('service_customer_name', models.CharField(max_length=15)),
                ('service_customer_phone', models.CharField(max_length=16)),
                ('sevice_customer_comment', models.TextField()),
                ('service_personal_info', models.BooleanField()),
                ('service_personal_reklama', models.BooleanField()),
            ],
        ),
    ]
