# Generated by Django 4.2 on 2023-05-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvtoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_model', models.CharField(max_length=50)),
                ('model_kuzov', models.CharField(max_length=10)),
                ('model_engin_capacity', models.CharField(max_length=3)),
                ('model_engin_power', models.CharField(max_length=3)),
                ('model_fuel', models.CharField(max_length=10)),
                ('model_transmission', models.CharField(max_length=4)),
                ('model_privod', models.CharField(max_length=10)),
                ('model_complectation', models.CharField(max_length=20)),
                ('model_cena', models.CharField(max_length=8)),
                ('model_ph_1', models.ImageField(upload_to='')),
                ('model_ph_2', models.ImageField(upload_to='')),
                ('model_ph_3', models.ImageField(upload_to='')),
            ],
        ),
    ]
