# Generated by Django 4.2 on 2023-05-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salone', '0002_avtomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allavto',
            name='kuzov',
        ),
        migrations.RemoveField(
            model_name='avtomodel',
            name='model_kuzov',
        ),
        migrations.AlterField(
            model_name='allavto',
            name='fuel',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Солярка', 'Солярка'), ('Газ', 'Газ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='allavto',
            name='mod_avto',
            field=models.CharField(choices=[('Patriot', 'Patriot'), ('Hunter', 'Hunter'), ('Пикап', 'Пикап'), ('Профи', 'Профи'), ('СГР', 'СГР')], max_length=7),
        ),
        migrations.AlterField(
            model_name='allavto',
            name='privod',
            field=models.CharField(choices=[('Полный привод', 'Полный привод')], max_length=13),
        ),
        migrations.AlterField(
            model_name='allavto',
            name='transmission',
            field=models.CharField(choices=[('МКПП', 'МКПП'), ('АКПП', 'АКПП')], default='МКПП', max_length=4),
        ),
        migrations.AlterField(
            model_name='avtomodel',
            name='model_fuel',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Солярка', 'Солярка'), ('Газ', 'Газ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='avtomodel',
            name='model_model',
            field=models.CharField(choices=[('Patriot', 'Patriot'), ('Hunter', 'Hunter'), ('Пикап', 'Пикап'), ('Профи', 'Профи'), ('СГР', 'СГР')], max_length=50),
        ),
        migrations.AlterField(
            model_name='avtomodel',
            name='model_privod',
            field=models.CharField(choices=[('МКПП', 'МКПП'), ('АКПП', 'АКПП')], max_length=10),
        ),
        migrations.AlterField(
            model_name='avtomodel',
            name='model_transmission',
            field=models.CharField(choices=[('МКПП', 'МКПП'), ('АКПП', 'АКПП')], max_length=4),
        ),
        migrations.AlterField(
            model_name='requestcall',
            name='call_mod_car',
            field=models.CharField(choices=[('Patriot', 'Patriot'), ('Hunter', 'Hunter'), ('Пикап', 'Пикап'), ('Профи', 'Профи'), ('СГР', 'СГР')], max_length=7),
        ),
        migrations.AlterField(
            model_name='requestcall',
            name='call_question_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requestcall',
            name='call_question_type',
            field=models.CharField(choices=[('Запись на тест-драйв', 'Запись на тест-драйв'), ('Запись на просмотр авто', 'Запись на просмотр авто'), ('Запись на консультацию', 'Запись на консультацию')], max_length=23),
        ),
    ]
