# Generated by Django 4.2 on 2023-05-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salone', '0003_remove_allavto_kuzov_remove_avtomodel_model_kuzov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avtomodel',
            name='model_privod',
            field=models.CharField(choices=[('Полный привод', 'Полный привод')], max_length=13),
        ),
    ]
