# Generated by Django 4.2 on 2023-05-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salone', '0004_alter_avtomodel_model_privod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceregistration',
            old_name='sevice_customer_comment',
            new_name='service_customer_comment',
        ),
        migrations.AlterField(
            model_name='allavto',
            name='fuel',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель')], max_length=10),
        ),
        migrations.AlterField(
            model_name='avtomodel',
            name='model_fuel',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель')], max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceregistration',
            name='service_mod_avto',
            field=models.CharField(choices=[('Patriot', 'Patriot'), ('Hunter', 'Hunter'), ('Пикап', 'Пикап'), ('Профи', 'Профи'), ('СГР', 'СГР')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceregistration',
            name='service_work_type',
            field=models.CharField(choices=[('Замена моторного масла и масляного фильтра', 'Замена моторного масла и масляного фильтра'), ('Промывка топливных баков', 'Промывка топливных баков'), ('Балансировка колес и перестановка по схеме', 'Балансировка колес и перестановка по схеме'), ('Диагностика систем управления двигателем, ABS/ESP', 'Диагностика систем управления двигателем, ABS/ESP'), ('Проверка суммарного люфта рулевого управления, свободного ходапедали тормоза', 'Проверка суммарного люфта рулевого управления, свободного ходапедали тормоза'), ('Проверка свечей зажигания', 'Проверка свечей зажигания'), ('Проверка состояни колес и шин', 'Проверка состояни колес и шин'), ('Проверка состония передней и задней подвески, карданных валов и защитных чехлов, проверка люфта подшипников ступиц колес', 'Проверка состония передней и задней подвески, карданных валов и защитных чехлов, проверка люфта подшипников ступиц колес'), ('Замена колес', 'Замена колес')], max_length=130),
        ),
    ]
